apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lp.fullname" . }}-secrets
type: Opaque
stringData:
  {{- if .Values.secrets.SESSION_SECRET }}
  SESSION_SECRET: "{{ .Values.secrets.SESSION_SECRET }}"
  {{- end }}
  {{- if .Values.secrets.DATABASE_URL }}
  DATABASE_URL: "{{ .Values.secrets.DATABASE_URL }}"
  {{- end }}
  {{- if .Values.secrets.AZURE_STORAGE_CONNECTION_STRING }}
  AZURE_STORAGE_CONNECTION_STRING: "{{ .Values.secrets.AZURE_STORAGE_CONNECTION_STRING }}"
  {{- end }}
  {{- if .Values.secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  AZURE_STORAGE_ACCOUNT_NAME: "{{ .Values.secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
  {{- end }}
  {{- if .Values.secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  AZURE_STORAGE_ACCOUNT_KEY: "{{ .Values.secrets.AZURE_STORAGE_ACCOUNT_KEY }}"
  {{- end }}
