apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learning-platform-ingress
  namespace: learning-platform
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    # - host: <YOUR_DOMAIN>
    -  http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learning-platform-service
                port:
                  number: 80
