apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: lp-identity
  namespace: learning-platform
spec:
  type: 0
  resourceID: "<YOUR-MANAGED-IDENTITY-RESOURCE-ID>"
  clientID: "<YOUR-MANAGED-IDENTITY-CLIENT-ID>"
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: lp-identity-binding
  namespace: learning-platform
spec:
  azureIdentity: lp-identity
  selector: learning-platform
