apiVersion: secrets-store.csi.x-k8s.io/v1 
kind: SecretProviderClass
metadata:
  name: lp-secret-provider
  namespace: learning-platform
  labels:
    name: learning-platform
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "selfhostedvault"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: AZURE_SQL_CONNECTION_STRING
          objectType: secret
        - |
          objectName: AZURE_STORAGE_CONNECTION_STRING
          objectType: secret
        - |
          objectName: SESSION_SECRET
          objectType: secret
    tenantId: "784f7653-7880-43d4-8bc3-f77cbbf0e3ab"
  secretObjects:
    - secretName: lp-secrets
      type: Opaque
      data:
        - objectName: AZURE_SQL_CONNECTION_STRING
          key: AZURE_SQL_CONNECTION_STRING
        - objectName: AZURE_STORAGE_CONNECTION_STRING
          key: AZURE_STORAGE_CONNECTION_STRING
        - objectName: SESSION_SECRET
          key: SESSION_SECRET
