apiVersion: v1
kind: Service
metadata:
  name: learning-platform-service
  namespace: learning-platform
spec:
  selector:
    app: learning-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
